Repository On-Rest/OnrRest-aOS, pull requests merged in 2023-12, with the labels that each got.

#22 🔀 :: [15] community recyclerview 추가
  README.md
  app/src/main/java/com/chobo/onrest/Community.kt
  app/src/main/java/com/chobo/onrest/CommunityAdapter.kt
  app/src/main/java/com/chobo/onrest/CommunityData.kt
  app/src/main/java/com/chobo/onrest/MainActivity.kt
  app/src/main/res/layout/calendar.xml
  app/src/main/res/layout/community.xml
  app/src/main/res/layout/comunity_list_view.xml
  app/src/main/res/layout/emotion_choice2_angry.xml
Labels: 0️⃣ Priority : Critical, ✨ Feature

#41 Post Deatil & simplify radius code
  app/src/main/java/com/chobo/onrest/PostDetailAdapter.kt
  app/src/main/java/com/chobo/onrest/PostDetailData.kt
  app/src/main/res/drawable/ctrlz.xml
  app/src/main/res/drawable/gray_toggle_color.xml
  app/src/main/res/drawable/ivory_toggle_color.xml
  app/src/main/res/drawable/memo_input.xml
  app/src/main/res/drawable/post_black_backgroundcolor.xml
  app/src/main/res/drawable/post_white_backgroundcolor.xml
  app/src/main/res/drawable/round_gray_eae9e7.xml
  app/src/main/res/drawable/round_square.xml
  app/src/main/res/drawable/round_white_18dp.xml
  app/src/main/res/drawable/round_white_f8f5f1.xml
  app/src/main/res/drawable/round_white_with_outline.xml
  app/src/main/res/layout/post_detail.xml
  app/src/main/res/layout/post_detail_list.xml
Labels: ✨ Feature

#46 🔀 :: space modify & font apply
  app/src/main/res/layout/post_detail.xml
  app/src/main/res/layout/post_detail_list.xml
Labels: 0️⃣ Priority : Critical, ⚡️ Simple

#57 🔀 :: UI 변경사항 반영해서 수정
  app/src/main/java/com/chobo/onrest/DataAdapter.kt
  app/src/main/java/com/chobo/onrest/Mission.kt
  app/src/main/res/drawable/post_detail_edit_text.xml
  app/src/main/res/layout/mission_list_view.xml
  app/src/main/res/layout/post_detail.xml
Labels: 2️⃣ Priority : Medium, ✨ Feature, ⚡️ Simple

#58 🔀 :: 변경된 UI 추가, 제거, 수정
  app/src/main/res/drawable/memo_input.xml
  app/src/main/res/layout/comunity_not_found.xml
  app/src/main/res/layout/diary_write.xml
Labels: 2️⃣ Priority : Medium, ✨ Feature, ⚡️ Simple

#60 🔀 :: add logout button
  app/src/main/res/drawable/logout_icon.xml
  app/src/main/res/layout/my_page.xml
Labels: 1️⃣ Priority : High, 🐞 Bug, ✨ Feature

#63 🔀 :: my_page pieChart
  app/src/main/java/com/chobo/onrest/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/my_page.xml
  app/src/main/res/layout/post_detail.xml
Labels: 0️⃣ Priority : Critical, ⚡️ performance

#66 🔀 :: UI change
  app/src/main/java/com/chobo/onrest/MainActivity.kt
  app/src/main/java/com/chobo/onrest/MyPageFragment.kt
  app/src/main/res/drawable/go_back_icon.xml
  app/src/main/res/drawable/login_google_button.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/calendar_click.xml
  app/src/main/res/layout/community.xml
  app/src/main/res/layout/diary_write.xml
  app/src/main/res/layout/post_write.xml
  app/src/main/res/layout/your_emotion.xml
Labels: 0️⃣ Priority : Critical, ⚡️ performance, ✨ Feature

#67 🔀 :: fix wrong icon
  app/src/main/res/layout/emotion_choice2_angry.xml
  app/src/main/res/layout/emotion_choice2_sad.xml
Labels: 0️⃣ Priority : Critical, ⚡️ Simple

#86 [#80] :: simple edit
  app/build.gradle.kts
  app/src/main/java/com/chobo/onrest/CalenderClick.kt
  app/src/main/java/com/chobo/onrest/IdTokenDataClass.kt
  app/src/main/java/com/chobo/onrest/MainActivity.kt
  app/src/main/java/com/chobo/onrest/NaviActivity.kt
  app/src/main/res/layout/activity_navi.xml
Labels: 2️⃣ Priority : Medium
